/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestSessionIdRouteImport } from './routes/test.$sessionId'
import { Route as ResultSessionIdRouteImport } from './routes/result.$sessionId'

const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestSessionIdRoute = TestSessionIdRouteImport.update({
  id: '/test/$sessionId',
  path: '/test/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultSessionIdRoute = ResultSessionIdRouteImport.update({
  id: '/result/$sessionId',
  path: '/result/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sessions': typeof SessionsRoute
  '/result/$sessionId': typeof ResultSessionIdRoute
  '/test/$sessionId': typeof TestSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sessions': typeof SessionsRoute
  '/result/$sessionId': typeof ResultSessionIdRoute
  '/test/$sessionId': typeof TestSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sessions': typeof SessionsRoute
  '/result/$sessionId': typeof ResultSessionIdRoute
  '/test/$sessionId': typeof TestSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sessions'
    | '/result/$sessionId'
    | '/test/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/sessions' | '/result/$sessionId' | '/test/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/sessions'
    | '/result/$sessionId'
    | '/test/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  SessionsRoute: typeof SessionsRoute
  ResultSessionIdRoute: typeof ResultSessionIdRoute
  TestSessionIdRoute: typeof TestSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/$sessionId': {
      id: '/test/$sessionId'
      path: '/test/$sessionId'
      fullPath: '/test/$sessionId'
      preLoaderRoute: typeof TestSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$sessionId': {
      id: '/result/$sessionId'
      path: '/result/$sessionId'
      fullPath: '/result/$sessionId'
      preLoaderRoute: typeof ResultSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  SessionsRoute: SessionsRoute,
  ResultSessionIdRoute: ResultSessionIdRoute,
  TestSessionIdRoute: TestSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
